Remove targets causing problems

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,12 +22,12 @@ jobs:
         targets:
           [
             'x86_64-unknown-linux-gnu',
-            'x86_64-unknown-linux-musl',
-            'aarch64-unknown-linux-gnu',
-            'aarch64-unknown-linux-musl',
-            'armv7-unknown-linux-gnueabihf',
-            'aarch64-linux-android',
-            'aarch64-pc-windows-msvc',
+            # 'x86_64-unknown-linux-musl',
+            # 'aarch64-unknown-linux-gnu',
+            # 'aarch64-unknown-linux-musl',
+            # 'armv7-unknown-linux-gnueabihf',
+            # 'aarch64-linux-android',
+            # 'aarch64-pc-windows-msvc',
           ]
     runs-on: ubuntu-latest
     name: Build for ${{ matrix.targets }}
@@ -119,15 +119,15 @@ jobs:
               clang --version
               pnpm build --target aarch64-apple-darwin
 
-          - host: ubuntu-latest
-            target: 'riscv64gc-unknown-linux-gnu'
-            downloadTarget: 'riscv64gc-unknown-linux-gnu'
-            build: |
-              sudo apt-get update
-              sudo apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu -y
-              export CC=riscv64-linux-gnu-gcc
-              export CXX=riscv64-linux-gnu-g++
-              pnpm build --target riscv64gc-unknown-linux-gnu
+          # - host: ubuntu-latest
+          #   target: 'riscv64gc-unknown-linux-gnu'
+          #   downloadTarget: 'riscv64gc-unknown-linux-gnu'
+          #   build: |
+          #     sudo apt-get update
+          #     sudo apt-get install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu -y
+          #     export CC=riscv64-linux-gnu-gcc
+          #     export CXX=riscv64-linux-gnu-g++
+          #     pnpm build --target riscv64gc-unknown-linux-gnu
 
     name: Build for ${{ matrix.settings.target }}
     runs-on: ${{ matrix.settings.host }}
@@ -216,8 +216,6 @@ jobs:
             target: 'aarch64-apple-darwin'
           - host: windows-latest
             target: 'x86_64-pc-windows-msvc'
-          - host: windows-latest
-            target: 'aarch64-pc-windows-msvc'
     runs-on: ${{ matrix.settings.host }}
     steps:
       - name: Checkout code
@@ -257,7 +255,7 @@ jobs:
         run: pnpm test
 
   test-linux-x64-gnu-binding:
-    name: Test bindings on Linux-x64-gnu
+    name: Test bindings on linux-x64-gnu
     needs:
       - cross-build
     strategy:
@@ -294,190 +292,189 @@ jobs:
       - name: Test bindings
         run: pnpm test
 
-  test-linux-x64-musl-binding:
-    name: Test bindings on x86_64-unknown-linux-musl
-    needs:
-      - cross-build
-    strategy:
-      fail-fast: false
-    runs-on: ubuntu-latest
+  # test-linux-x64-musl-binding:
+  #   name: Test bindings on linux-x64-musl
+  #   needs:
+  #     - cross-build
+  #   strategy:
+  #     fail-fast: false
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         version: 9
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          version: 9
+  #     - name: Setup node
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 22
+  #         cache: pnpm
 
-      - name: Setup node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 22
-          cache: pnpm
+  #     - name: Install dependencies
+  #       run: |
+  #         pnpm config set supportedArchitectures.libc "musl"
+  #         pnpm install
 
-      - name: Install dependencies
-        run: |
-          pnpm config set supportedArchitectures.libc "musl"
-          pnpm install
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: bindings-x86_64-unknown-linux-musl
+  #         path: .
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: bindings-x86_64-unknown-linux-musl
-          path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
 
-      - name: List packages
-        run: ls -R .
-        shell: bash
+  #     - name: Test bindings
+  #       run: docker run --rm -v $(pwd):/webp -w /webp node:22-alpine npm i -g pnpm && pnpm test
 
-      - name: Test bindings
-        run: docker run --rm -v $(pwd):/webp -w /webp node:22-alpine npm i -g pnpm && pnpm test
+  # test-linux-aarch64-gnu-binding:
+  #   name: Test bindings on linux-aarch64-gnu
+  #   needs:
+  #     - cross-build
+  #   strategy:
+  #     fail-fast: false
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-  test-linux-aarch64-gnu-binding:
-    name: Test bindings on aarch64-unknown-linux-gnu
-    needs:
-      - cross-build
-    strategy:
-      fail-fast: false
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         version: 9
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          version: 9
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: bindings-aarch64-unknown-linux-gnu
+  #         path: .
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: bindings-aarch64-unknown-linux-gnu
-          path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
 
-      - name: List packages
-        run: ls -R .
-        shell: bash
+  #     - name: Install dependencies
+  #       run: |
+  #         pnpm config set supportedArchitectures.cpu "arm64"
+  #         pnpm config set supportedArchitectures.libc "glibc"
+  #         pnpm install
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #       with:
+  #         platforms: arm64
 
-      - name: Install dependencies
-        run: |
-          pnpm config set supportedArchitectures.cpu "arm64"
-          pnpm config set supportedArchitectures.libc "glibc"
-          pnpm install
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-        with:
-          platforms: arm64
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 
-      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: node:22-slim
+  #         options: '--platform linux/arm64 -v ${{ github.workspace }}:/webp -w /webp'
+  #         run: |
+  #           set -e && \
+  #           npm run test && \
+  #           ls -la
 
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:22-slim
-          options: '--platform linux/arm64 -v ${{ github.workspace }}:/webp -w /webp'
-          run: |
-            set -e && \
-            npm run test && \
-            ls -la
+  # test-linux-aarch64-musl-binding:
+  #   name: Test bindings on aarch64-unknown-linux-musl
+  #   needs:
+  #     - cross-build
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-  test-linux-aarch64-musl-binding:
-    name: Test bindings on aarch64-unknown-linux-musl
-    needs:
-      - cross-build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         version: 9
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          version: 9
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: bindings-aarch64-unknown-linux-musl
+  #         path: .
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: bindings-aarch64-unknown-linux-musl
-          path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
 
-      - name: List packages
-        run: ls -R .
-        shell: bash
+  #     - name: Install dependencies
+  #       run: |
+  #         pnpm config set supportedArchitectures.cpu "arm64"
+  #         pnpm config set supportedArchitectures.libc "musl"
+  #         pnpm install
 
-      - name: Install dependencies
-        run: |
-          pnpm config set supportedArchitectures.cpu "arm64"
-          pnpm config set supportedArchitectures.libc "musl"
-          pnpm install
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #       with:
+  #         platforms: arm64
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-        with:
-          platforms: arm64
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 
-      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: node:lts-alpine
+  #         options: '--platform linux/arm64 -v ${{ github.workspace }}:/webp -w /webp'
+  #         run: |
+  #           set -e
+  #           npm install -g pnpm
+  #           pnpm test
 
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:lts-alpine
-          options: '--platform linux/arm64 -v ${{ github.workspace }}:/webp -w /webp'
-          run: |
-            set -e
-            npm install -g pnpm
-            pnpm test
+  # test-linux-arm-gnueabihf-binding:
+  #   name: Test bindings on armv7-unknown-linux-gnueabihf
+  #   needs:
+  #     - cross-build
+  #   strategy:
+  #     fail-fast: false
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-  test-linux-arm-gnueabihf-binding:
-    name: Test bindings on armv7-unknown-linux-gnueabihf
-    needs:
-      - cross-build
-    strategy:
-      fail-fast: false
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         version: 9
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          version: 9
+  #     - name: Download artifacts
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: bindings-armv7-unknown-linux-gnueabihf
+  #         path: .
 
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: bindings-armv7-unknown-linux-gnueabihf
-          path: .
+  #     - name: List packages
+  #       run: ls -R .
+  #       shell: bash
 
-      - name: List packages
-        run: ls -R .
-        shell: bash
+  #     - name: Install dependencies
+  #       run: |
+  #         pnpm config set supportedArchitectures.cpu "arm"
+  #         pnpm install
 
-      - name: Install dependencies
-        run: |
-          pnpm config set supportedArchitectures.cpu "arm"
-          pnpm install
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #       with:
+  #         platforms: arm
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-        with:
-          platforms: arm
+  #     - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
 
-      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
-
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: node:22-bullseye-slim
-          options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/webp -w /webp'
-          run: |
-            set -e && \
-            npm install -g pnpm && \
-            pnpm test && \
-            ls -la
+  #     - name: Setup and run tests
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: node:22-bullseye-slim
+  #         options: '--platform linux/arm/v7 -v ${{ github.workspace }}:/webp -w /webp'
+  #         run: |
+  #           set -e && \
+  #           npm install -g pnpm && \
+  #           pnpm test && \
+  #           ls -la
 
   publish:
     name: Publish
